version: '3.7'

services:
# nginx section (web server)
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "4443:443"
    links:
      - fpm
    volumes:
      - ./:/var/www/laravel
      - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/laravel.conf
    working_dir:
      /var/www

# php section
  fpm:
    container_name: fpm
    image: bdaler/php74-image-for-laravel:1.0
    links:
      - db
    volumes:
      - ./:/var/www/laravel
    working_dir:
      /var/www/laravel
#db section
  db:
    image: postgres:12.3
    restart: always
    container_name: db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: 'laravel'
      POSTGRES_DB: 'laravel'
      POSTGRES_PASSWORD: 'laravel'
#db_for_test section
  db_test:
    image: postgres:12.3
    restart: always
    container_name: db_test
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: 'laravel_test'
      POSTGRES_DB: 'laravel_test'
      POSTGRES_PASSWORD: 'laravel_test'
